Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [4]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Answer 1: Yes, there is difference in the data type of variables list_ and array_list. list_ is a list whereas array_list is a 1D array. 

In [5]:
# data type of list_ 
type(list_)

list

In [6]:
# data type of array_list
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [8]:
# Answer 2: 
# data type of each element of list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
# data type of each element of array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
# Answer 3: 
array_list = np.array(object = list_, dtype = int)

Yes, there will be difference in the data type of the elements present in array_list. But there won't be any difference in the data type of the elements present in list_.

In [13]:
# data type of each element of list_. There is no change in the data types of the elements of list_.
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
# data type of each element of array_list. Previously it contained all the elements of string data type and now it contains int data type elements.
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [24]:
# Answer 4: 
# (i) shape.... It gives the tuple of number of rows and columns
shape=num_array.shape
print(shape)

(2, 3)


In [25]:
# (ii) size.... It gives the total number of elements in the 2D array
size=num_array.size
print(size)

6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
# Answer 5: 
zero_matrix=np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [22]:
# Answer 6: 
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
